// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset_management_svr/internal/dao/internal"
)

// assetProductDao is the data access object for the table asset_product.
// You can define custom methods on it to extend its functionality as needed.
type assetProductDao struct {
	*internal.AssetProductDao
}

var (
	// AssetProduct is a globally accessible object for table asset_product operations.
	AssetProduct = assetProductDao{internal.NewAssetProductDao()}
)

// Add your custom methods and functionality below.
