// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset_management_svr/internal/dao/internal"
)

// assetItemDao is the data access object for the table asset_item.
// You can define custom methods on it to extend its functionality as needed.
type assetItemDao struct {
	*internal.AssetItemDao
}

var (
	// AssetItem is a globally accessible object for table asset_item operations.
	AssetItem = assetItemDao{internal.NewAssetItemDao()}
)

// Add your custom methods and functionality below.
