// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset_management_svr/internal/dao/internal"
)

// assetLocationRecordDao is the data access object for the table asset_location_record.
// You can define custom methods on it to extend its functionality as needed.
type assetLocationRecordDao struct {
	*internal.AssetLocationRecordDao
}

var (
	// AssetLocationRecord is a globally accessible object for table asset_location_record operations.
	AssetLocationRecord = assetLocationRecordDao{internal.NewAssetLocationRecordDao()}
)

// Add your custom methods and functionality below.
