// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset_management_svr/internal/dao/internal"
)

// assetBuildingDao is the data access object for the table asset_building.
// You can define custom methods on it to extend its functionality as needed.
type assetBuildingDao struct {
	*internal.AssetBuildingDao
}

var (
	// AssetBuilding is a globally accessible object for table asset_building operations.
	AssetBuilding = assetBuildingDao{internal.NewAssetBuildingDao()}
)

// Add your custom methods and functionality below.
