// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset_management_svr/internal/dao/internal"
)

// assetRoomDao is the data access object for the table asset_room.
// You can define custom methods on it to extend its functionality as needed.
type assetRoomDao struct {
	*internal.AssetRoomDao
}

var (
	// AssetRoom is a globally accessible object for table asset_room operations.
	AssetRoom = assetRoomDao{internal.NewAssetRoomDao()}
)

// Add your custom methods and functionality below.
