// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset_management_svr/internal/dao/internal"
)

// assetCategoryDao is the data access object for the table asset_category.
// You can define custom methods on it to extend its functionality as needed.
type assetCategoryDao struct {
	*internal.AssetCategoryDao
}

var (
	// AssetCategory is a globally accessible object for table asset_category operations.
	AssetCategory = assetCategoryDao{internal.NewAssetCategoryDao()}
)

// Add your custom methods and functionality below.
