// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"asset_management_svr/internal/dao/internal"
)

// assetFloorDao is the data access object for the table asset_floor.
// You can define custom methods on it to extend its functionality as needed.
type assetFloorDao struct {
	*internal.AssetFloorDao
}

var (
	// AssetFloor is a globally accessible object for table asset_floor operations.
	AssetFloor = assetFloorDao{internal.NewAssetFloorDao()}
)

// Add your custom methods and functionality below.
